/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountsInfoRequestItem {
    /**
    * ID of the block chain
    */
    'chainId': AccountsInfoRequestItem.ChainIdEnum;
    /**
    *  Blockchain network to get the account info from. For XRP this would be one of (testnet/devnet/mainnet). More information regarding what environments are available can be obtained from /v1/blockchains/{chainId}/status endpoint. This field is required if `fee` is not specified in order to dynamically obtain the fee from the network. 
    */
    'network'?: string;
    /**
    * Identifier representing the account. This is most likely the wallet address.
    */
    'accountId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "AccountsInfoRequestItem.ChainIdEnum"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountsInfoRequestItem.attributeTypeMap;
    }
}

export namespace AccountsInfoRequestItem {
    export enum ChainIdEnum {
        xrp = <any> 'xrp',
        eth = <any> 'eth'
    }
}
