/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CurrencyValue } from './currencyValue';
import { GenericCurrencyValue } from './genericCurrencyValue';
import { ServerErrorObject } from './serverErrorObject';
import { SubAccountInfo } from './subAccountInfo';

/**
* Represents information regarding a blockchain wallet / account.
*/
export class BlockchainAccountInfo {
    'chainId'?: BlockchainAccountInfo.ChainIdEnum;
    'network'?: string;
    'server'?: string;
    'accountId'?: string;
    'balance'?: CurrencyValue;
    'value'?: GenericCurrencyValue;
    /**
    * List of sub accounts and their balances. ERC20 tokens and their balances in case of ethereum.
    */
    'subAccounts'?: Array<SubAccountInfo>;
    'lastTransactionId'?: string;
    /**
    * Current ledger nonce or index
    */
    'nonce'?: string;
    'errors'?: Array<ServerErrorObject>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "BlockchainAccountInfo.ChainIdEnum"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "CurrencyValue"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "GenericCurrencyValue"
        },
        {
            "name": "subAccounts",
            "baseName": "subAccounts",
            "type": "Array<SubAccountInfo>"
        },
        {
            "name": "lastTransactionId",
            "baseName": "lastTransactionId",
            "type": "string"
        },
        {
            "name": "nonce",
            "baseName": "nonce",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ServerErrorObject>"
        }    ];

    static getAttributeTypeMap() {
        return BlockchainAccountInfo.attributeTypeMap;
    }
}

export namespace BlockchainAccountInfo {
    export enum ChainIdEnum {
        Xrp = <any> 'xrp',
        Eth = <any> 'eth'
    }
}
