/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlockchainAccountTransactionItem } from './blockchainAccountTransactionItem';

/**
* Represents a blockchain account transaction.
*/
export class BlockchainAccountTransaction {
    'chainId'?: BlockchainAccountTransaction.ChainIdEnum;
    'network'?: string;
    'server'?: string;
    'transaction'?: BlockchainAccountTransactionItem;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "BlockchainAccountTransaction.ChainIdEnum"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "BlockchainAccountTransactionItem"
        }    ];

    static getAttributeTypeMap() {
        return BlockchainAccountTransaction.attributeTypeMap;
    }
}

export namespace BlockchainAccountTransaction {
    export enum ChainIdEnum {
        Xrp = <any> 'xrp',
        Eth = <any> 'eth'
    }
}
