/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Simple object representing `amount` as string in a specific `currency`.
*/
export class CurrencyValue {
    'amount': string;
    'issuer'?: string | null;
    'currency': CurrencyValue.CurrencyEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CurrencyValue.CurrencyEnum"
        }    ];

    static getAttributeTypeMap() {
        return CurrencyValue.attributeTypeMap;
    }
}

export namespace CurrencyValue {
    export enum CurrencyEnum {
        Xrp = <any> 'xrp',
        Drops = <any> 'drops',
        Eth = <any> 'eth',
        Gas = <any> 'gas'
    }
}
