/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorResponse } from './errorResponse';

export class InvalidAccountAddressError {
    /**
    * Indicates when the error occurred
    */
    'timestamp'?: number;
    /**
    * HTTP status code of the error
    */
    'status'?: number;
    /**
    * HTTP status description
    */
    'error'?: string;
    /**
    * Error message describing the error in detail
    */
    'message'?: string;
    /**
    * The endpoint that caused this error
    */
    'path'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InvalidAccountAddressError.attributeTypeMap;
    }
}

