/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MarketsItem } from './marketsItem';

/**
* Object containing list of available markets
*/
export class MarketsResponse {
    /**
    * List of market objects
    */
    'markets'?: Array<MarketsItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "markets",
            "baseName": "markets",
            "type": "Array<MarketsItem>"
        }    ];

    static getAttributeTypeMap() {
        return MarketsResponse.attributeTypeMap;
    }
}

