/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object describing a specific market
*/
export class MarketsItem {
    /**
    * Name of the market, typically name of the exchange
    */
    'name'?: string;
    /**
    * Market status
    */
    'status'?: MarketsItem.StatusEnum;
    /**
    * Supported list of currencies for this market
    */
    'currencies'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MarketsItem.StatusEnum"
        },
        {
            "name": "currencies",
            "baseName": "currencies",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return MarketsItem.attributeTypeMap;
    }
}

export namespace MarketsItem {
    export enum StatusEnum {
        Connected = <any> 'connected',
        Disconnected = <any> 'disconnected'
    }
}
