/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Describes order at an exchange
*/
export class Order {
    /**
    * Type of the order
    */
    'type'?: Order.TypeEnum;
    /**
    * Order amount
    */
    'amount'?: number;
    /**
    * Order ID
    */
    'id'?: string;
    /**
    * Order timestamp (ms since epoch)
    */
    'timestamp'?: string;
    /**
    * Order price
    */
    'price'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "Order.TypeEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Order.attributeTypeMap;
    }
}

export namespace Order {
    export enum TypeEnum {
        Bid = <any> 'BID',
        Ask = <any> 'ASK',
        ExitBid = <any> 'EXIT_BID',
        ExitAsk = <any> 'EXIT_ASK'
    }
}
