/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Order } from './order';

/**
* Represents an order book containing list of asks and bids
*/
export class OrderBook {
    /**
    * Base currency
    */
    'base'?: string;
    /**
    * Counter currency
    */
    'counter'?: string;
    /**
    * Name of the exchanges (multiple if this is an aggregated orderbook)
    */
    'exchanges'?: Array<string>;
    /**
    * Order timestamp (ms since epoch)
    */
    'timestamp'?: string;
    /**
    * Lists of asks
    */
    'asks'?: Array<Order>;
    /**
    * Lists of bids
    */
    'bids'?: Array<Order>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "base",
            "baseName": "base",
            "type": "string"
        },
        {
            "name": "counter",
            "baseName": "counter",
            "type": "string"
        },
        {
            "name": "exchanges",
            "baseName": "exchanges",
            "type": "Array<string>"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "asks",
            "baseName": "asks",
            "type": "Array<Order>"
        },
        {
            "name": "bids",
            "baseName": "bids",
            "type": "Array<Order>"
        }    ];

    static getAttributeTypeMap() {
        return OrderBook.attributeTypeMap;
    }
}

