/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Rate } from './rate';

export class RateResponse {
    'avg'?: Rate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avg",
            "baseName": "avg",
            "type": "Rate"
        }    ];

    static getAttributeTypeMap() {
        return RateResponse.attributeTypeMap;
    }
}

