/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ServerStatusResponseErrors } from './serverStatusResponseErrors';

/**
* Represents the status of the Key Connect server.
*/
export class ServerStatusResponse {
    /**
    * Status of the server
    */
    'status'?: ServerStatusResponse.StatusEnum;
    /**
    * Any server errors if the server is unhealthy
    */
    'errors'?: Array<ServerStatusResponseErrors>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ServerStatusResponse.StatusEnum"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ServerStatusResponseErrors>"
        }    ];

    static getAttributeTypeMap() {
        return ServerStatusResponse.attributeTypeMap;
    }
}

export namespace ServerStatusResponse {
    export enum StatusEnum {
        healthy = <any> 'healthy',
        unhealthy = <any> 'unhealthy'
    }
}
