/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents information regarding a error.
*/
export class ServerErrorObject {
    /**
    * Error category
    */
    'category'?: ServerErrorObject.CategoryEnum;
    /**
    * Error severity
    */
    'severity'?: ServerErrorObject.SeverityEnum;
    /**
    * Error message
    */
    'message'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "ServerErrorObject.CategoryEnum"
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "ServerErrorObject.SeverityEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ServerErrorObject.attributeTypeMap;
    }
}

export namespace ServerErrorObject {
    export enum CategoryEnum {
        blockchain = <any> 'blockchain',
        database = <any> 'database',
        internal = <any> 'internal'
    }
    export enum SeverityEnum {
        critical = <any> 'critical',
        high = <any> 'high',
        medium = <any> 'medium',
        low = <any> 'low',
        warning = <any> 'warning',
        info = <any> 'info'
    }
}
