/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GenericCurrencyValue } from './genericCurrencyValue';

/**
* Represents a sub-account. ERC20 token account in case of ethereum.
*/
export class SubAccountInfo {
    /**
    * ID of the sub account. Contract hash in case of ethereum token.
    */
    'accountId'?: string;
    'balance'?: GenericCurrencyValue;
    'value'?: GenericCurrencyValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "GenericCurrencyValue"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "GenericCurrencyValue"
        }    ];

    static getAttributeTypeMap() {
        return SubAccountInfo.attributeTypeMap;
    }
}

