/**
 * Key Connect API
 * Blockchain access made simple
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: manthan@keyconnect.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BlockchainAccountTransactionItem } from './blockchainAccountTransactionItem';

/**
* Represents the result of the submission of a given blockchain transaction.
*/
export class SubmitTransactionResult {
    'chainId'?: SubmitTransactionResult.ChainIdEnum;
    'network'?: string;
    'server'?: string;
    'transaction'?: BlockchainAccountTransactionItem;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "SubmitTransactionResult.ChainIdEnum"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "BlockchainAccountTransactionItem"
        }    ];

    static getAttributeTypeMap() {
        return SubmitTransactionResult.attributeTypeMap;
    }
}

export namespace SubmitTransactionResult {
    export enum ChainIdEnum {
        xrp = <any> 'xrp',
        eth = <any> 'eth',
        btc = <any> 'btc'
    }
}
